sheets:
  Parameters:
    data_row_start: 1
    # zero-based row index
    # For example, if you want to freeze the first row, set this to 1.
    freeze_pane_row: 1
    # zero-based col index
    # For example, if you want to freeze the first column, set this to 1.
    freeze_pane_col: 1
    columns:
      A:
        width: 200
      B:
        width: 100
    rows:
      0:
        height: 50
        format:
          bold: true
          italic: true
          underline: true
          font_size: 12
          font_color: red
          background_color: yellow
  NV Memory:
    columns:
      A:
        width: 100
      B:
        width: 100
